import { Patient } from "./workflow";

const now = Date.now();
const hrsAgo = (h: number) => new Date(now - h * 3600_000).toISOString();

export const SEED_PATIENTS: Patient[] = [
  {
    id: "p-001",
    name: "Marcus Reed",
    dob: "1978-04-12",
    product: "CGM",
    payer: "BCBS Texas",
    doctorName: "Dr. Elena Voss",
    doctorClinic: "Voss Endocrinology",
    contactMethod: "parachute",
    pathwayId: "cgm-p1",
    stage: "evaluation",
    pillars: { rx: true, records: true, diagnosis: true },
    pathwayChecks: { "insulin-evidence": true, "insulin-meds": true },
    chaseStep: 0,
    faxPhase: 1,
    notes: "",
    receivedAt: hrsAgo(2),
    lastUpdated: hrsAgo(1),
    owner: "Masheke",
  },
  {
    id: "p-002",
    name: "Priya Nair",
    dob: "1965-09-30",
    product: "Pump",
    payer: "Aetna",
    doctorName: "Dr. James Holloway",
    doctorClinic: "Holloway Diabetes Center",
    contactMethod: "fax",
    pathwayId: "pump-p1",
    stage: "doctor-request",
    pillars: { rx: true, records: false, diagnosis: true },
    pathwayChecks: {},
    chaseStep: 1,
    faxPhase: 1,
    accountability: {
      representativeName: "Elaine Ortiz",
      representativeTitle: "Lead RN",
      confirmedAt: hrsAgo(26),
    },
    notes: "",
    receivedAt: hrsAgo(72),
    lastUpdated: hrsAgo(20),
    owner: "Masheke",
  },
  {
    id: "p-003",
    name: "Daniel Okafor",
    dob: "1982-01-22",
    product: "CGM + Pump",
    payer: "United Healthcare",
    doctorName: "Dr. Sarah Lin",
    doctorClinic: "Lin Family Medicine",
    contactMethod: "parachute",
    pathwayId: "cgm-p2",
    stage: "doctor-request",
    pillars: { rx: true, records: true, diagnosis: true },
    pathwayChecks: { "hypo-event": true, "hypo-adjustments": false },
    chaseStep: 2,
    faxPhase: 1,
    notes: "",
    receivedAt: hrsAgo(120),
    lastUpdated: hrsAgo(48),
    owner: "Masheke",
  },
  {
    id: "p-004",
    name: "Hana Whitfield",
    dob: "1990-07-08",
    product: "Pump",
    payer: "Cigna",
    doctorName: "Dr. Ravi Patel",
    doctorClinic: "Patel Endo Group",
    contactMethod: "fax",
    pathwayId: "pump-p3",
    stage: "escalated",
    pillars: { rx: true, records: true, diagnosis: true },
    pathwayChecks: { oow: true, malfunction: true, "no-repair": false },
    chaseStep: 3,
    faxPhase: 2,
    accountability: {
      representativeName: "Marcus Bell",
      representativeTitle: "Office Manager",
      confirmedAt: hrsAgo(96),
    },
    notes: "",
    receivedAt: hrsAgo(240),
    lastUpdated: hrsAgo(4),
    owner: "Janelle",
  },
  {
    id: "p-005",
    name: "Theo Sandoval",
    dob: "1955-12-03",
    product: "Supplies",
    payer: "Medicare",
    doctorName: "Dr. Aisha Brooks",
    doctorClinic: "Brooks Internal Medicine",
    contactMethod: "parachute",
    pathwayId: "supplies-s1",
    stage: "advanced",
    pillars: { rx: true, records: true, diagnosis: true },
    pathwayChecks: { established: true },
    chaseStep: 0,
    faxPhase: 1,
    notes: "",
    receivedAt: hrsAgo(48),
    lastUpdated: hrsAgo(6),
    owner: "Samantha",
    hasMedicaid: false,
    insurance: {
      universal: { "in-network": true, active: true, "dme-benefits": true },
      codes: {
        pump: { status: "clear" },
        "infusion-sets": { status: "pending", selectedCode: "A4230" },
        cartridges: { status: "pending" },
      },
    },
  },
  {
    id: "p-006",
    name: "Wren Castellano",
    dob: "1988-03-19",
    product: "Pump",
    payer: "Humana",
    doctorName: "Dr. Marcus Chen",
    doctorClinic: "Chen Diabetes Clinic",
    contactMethod: "fax",
    stage: "intake",
    pillars: { rx: false, records: false, diagnosis: false },
    pathwayChecks: {},
    chaseStep: 0,
    faxPhase: 1,
    notes: "",
    receivedAt: hrsAgo(0.5),
    lastUpdated: hrsAgo(0.5),
    owner: "Masheke",
  },
  {
    id: "p-007",
    name: "Lila Frenkel",
    dob: "1972-11-14",
    product: "CGM",
    payer: "Anthem BCBS",
    doctorName: "Dr. Imani Carter",
    doctorClinic: "Carter Endocrinology",
    contactMethod: "parachute",
    pathwayId: "cgm-p1",
    stage: "advanced",
    pillars: { rx: true, records: true, diagnosis: true },
    pathwayChecks: { "insulin-evidence": true, "insulin-meds": true },
    chaseStep: 0,
    faxPhase: 1,
    notes: "",
    receivedAt: hrsAgo(72),
    lastUpdated: hrsAgo(2),
    owner: "Samantha",
    hasMedicaid: false,
    insurance: {
      universal: { "in-network": true, active: true, "dme-benefits": true },
      codes: {
        "cgm-monitor": { status: "auth-required", authSubmittedAt: hrsAgo(20) },
        "cgm-sensors": { status: "clear" },
      },
    },
  },
];
